Repository Beyond-Article1/article1, pull requests merged in 2024-11, with the labels that each got.

#8 feat: #7 예외처리 핸들러 생성, 사용자 정의 예외 생성
  article1_be/article1-be/src/main/java/article1be/common/exception/CustomException.java
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorCode.java
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorResponse.java
  article1_be/article1-be/src/main/java/article1be/common/exception/GlobalExceptionHandler.java
  article1_be/article1-be/src/main/java/article1be/common/test.md
Labels: :new: feat, :1234: chore

#17 Delete article1_be/article1-be/.env
  article1_be/article1-be/.env
Labels: :1234: chore

#20 feat: #10 openweather의 5day를 통해 3시간 간격의 날씨 정보를 가져온다 , feat: #18 openw…
  .gitignore
  article1_be/.idea/workspace.xml
  article1_be/article1-be/src/main/java/article1be/Article1BeApplication.java
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeather5DayDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherAirDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
Labels: :new: feat, :1234: chore

#22 feat: #21 gradle 환경변수 설정
  article1_be/article1-be/build.gradle
Labels: :new: feat, :1234: chore

#25 feat: #24 현재~다음날 00시 이전까지의 데이터 생성, 시간포맷 관련 util클래스 생성, 날씨 및 대기질 DTO 공…
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorCode.java
  article1_be/article1-be/src/main/java/article1be/common/utils/DateTimeUtil.java
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeather5DayDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherAirDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/ResponseTodayDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/airs/AirListDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/airs/ComponentsDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/airs/MainAirDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/CityDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/CloudsDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/CoordDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/MainDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/RainDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/SnowDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/SysDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/WeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/WeatherListDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/WindDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
Labels: :wastebasket: delete, :recycle: refactor, :new: feat, :1234: chore

#35 [Feat/appointment data/#29]
  article1_be/article1-be/src/main/java/article1be/common/utils/DateTimeUtil.java
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ChangeMainDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ChangeWeatherListDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ResponseAppointDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ResponseTodayDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
Labels: :recycle: refactor, :new: feat, :1234: chore

#37 feat: #36 지정시간에 관한 날씨코드, 온도, 체감 온도, 날씨아이콘, 미세먼지 농도, 초미세먼지 농도, 지정시간 ~ 다음날 00시의 (최저기온, 최고기온)
  article1_be/article1-be/src/main/java/article1be/common/utils/DateTimeUtil.java
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/airs/ComponentsDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ResponseMainWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitService.java
Labels: :recycle: refactor, :new: feat, :1234: chore

#38 [FEAT][REFACTOR] 추천 알고리즘 반환값 수정 및 선택기록, 선택복장 저장 구현
  article1_be/article1-be/src/main/java/article1be/outfit/controller/OutfitController.java
  article1_be/article1-be/src/main/java/article1be/outfit/dto/OutfitResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/outfit/dto/OutfitSelectionRequestDTO.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/Outfit.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/SelectOutfit.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/SelectRecord.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectOutfitRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectRecordRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitSelectionService.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitService.java
  article1_be/article1-be/src/main/resources/data.sql
Labels: :hammer_and_wrench: fix, :recycle: refactor, :new: feat

#41 chore: #40 BaseTimeEntity 수정
  article1_be/article1-be/src/main/java/article1be/common/aggregate/entity/BaseTimeEntity.java
Labels: :1234: chore

#43 feat: #42 docker-compose DB 환경 구축 및 볼륨 설정
  docker-compose.yml
Labels: :new: feat

#45 feat: #44 회원 개인정보 관련 기능 구현
  article1_be/article1-be/build.gradle
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorCode.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserDataDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserUpdateDTO.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserAuth.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserGender.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserSocialSite.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserState.java
  article1_be/article1-be/src/main/java/article1be/user/repository/UserRepository.java
  article1_be/article1-be/src/main/java/article1be/user/service/KakaoService.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_be/article1-be/src/main/resources/Schema.sql
  article1_be/article1-be/src/main/resources/data.sql
Labels: :new: feat, :1234: chore

#46 [FEAT] cors 적용
  article1_be/article1-be/src/main/java/article1be/config/WebConfig.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitService.java
Labels: :hammer_and_wrench: fix, :new: feat

#48 chore: #47 스프링부트 .env 파일 인식오류 수정
  article1_be/article1-be/build.gradle
  article1_be/article1-be/src/main/resources/application.yml
Labels: :1234: chore

#52 [feat] 파일 구조 설정
  article1_fe/article1-fe/src/assets/images/test
  article1_fe/article1-fe/src/components/location/test
  article1_fe/article1-fe/src/config/test
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/store/test
  article1_fe/article1-fe/src/views/location/test
Labels: :m: test

#54 FEAT : #27 리뷰 기능 구현
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorCode.java
  article1_be/article1-be/src/main/java/article1be/review/aggregate/entity/Review.java
  article1_be/article1-be/src/main/java/article1be/review/controller/ReviewController.java
  article1_be/article1-be/src/main/java/article1be/review/dto/ReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/review/repository/ReviewRepository.java
  article1_be/article1-be/src/main/java/article1be/review/service/ReviewService.java
Labels: :new: feat, :1234: chore

#57 feat: #9 소셜 로그인 (Naver, Google) 기능 구현
  article1_be/article1-be/build.gradle
  article1_be/article1-be/src/main/java/article1be/config/GoogleUserInfo.java
  article1_be/article1-be/src/main/java/article1be/config/NaverUserInfo.java
  article1_be/article1-be/src/main/java/article1be/config/OAuth2UserInfo.java
  article1_be/article1-be/src/main/java/article1be/config/PrincipalDetails.java
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/user/controller/NaverAndGoogleController.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/repository/UserRepository.java
  article1_be/article1-be/src/main/java/article1be/user/service/NaverAndGoogleService.java
  article1_be/article1-be/src/main/resources/application.yml
  article1_be/article1-be/src/main/resources/data.sql
  article1_be/article1-be/src/main/resources/templates/loginForm.html
Labels: :new: feat, :1234: chore

#60 chore: #9 UserController 수정
  article1_be/article1-be/src/main/java/article1be/config/NaverUserInfo.java
  article1_be/article1-be/src/main/java/article1be/config/OAuth2UserInfo.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
Labels: :1234: chore

#63 [feat/main-page/#59] #59 메인페이지 작성, 라우터 변형 및 추가
  article1_fe/article1-fe/package-lock.json
  article1_fe/article1-fe/package.json
  article1_fe/article1-fe/src/App.vue
  article1_fe/article1-fe/src/assets/images/back-main.png
  article1_fe/article1-fe/src/main.js
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/router/mainRouter.js
  article1_fe/article1-fe/src/views/main/MainView.vue
Labels: :new: feat, :1234: chore

#67 feat: 게시판, 댓글 기능 구현
  .gitignore
  article1_be/article1-be/build.gradle
  article1_be/article1-be/src/main/java/article1be/amazonS3/service/AmazonS3Service.java
  article1_be/article1-be/src/main/java/article1be/board/controller/BoardController.java
  article1_be/article1-be/src/main/java/article1be/board/dto/BoardDTO.java
  article1_be/article1-be/src/main/java/article1be/board/dto/PictureDTO.java
  article1_be/article1-be/src/main/java/article1be/board/dto/RequestBoard.java
  article1_be/article1-be/src/main/java/article1be/board/dto/RequestPicture.java
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/board/entity/Picture.java
  article1_be/article1-be/src/main/java/article1be/board/repository/BoardRepository.java
  article1_be/article1-be/src/main/java/article1be/board/repository/PictureRepository.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
  article1_be/article1-be/src/main/java/article1be/config/S3Config.java
  article1_be/article1-be/src/main/java/article1be/reply/controller/ReplyController.java
  article1_be/article1-be/src/main/java/article1be/reply/dto/ReplyDTO.java
  article1_be/article1-be/src/main/java/article1be/reply/dto/RequestReply.java
  article1_be/article1-be/src/main/java/article1be/reply/entity/Reply.java
  article1_be/article1-be/src/main/java/article1be/reply/repository/ReplyRepository.java
  article1_be/article1-be/src/main/java/article1be/reply/service/ReplyService.java
  article1_be/article1-be/src/main/resources/application.yml
Labels: :hammer_and_wrench: fix, :new: feat

#66 feat : #62 관리자 리뷰 조회 및 리뷰 코드 수정
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminController.java
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminReviewController.java
  article1_be/article1-be/src/main/java/article1be/admin/dto/AdminDTO.java
  article1_be/article1-be/src/main/java/article1be/admin/dto/AdminReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/admin/repository/AdminReviewRepository.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminReviewService.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminService.java
  article1_be/article1-be/src/main/java/article1be/review/controller/ReviewController.java
  article1_be/article1-be/src/main/java/article1be/review/dto/ReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/review/entity/Review.java
  article1_be/article1-be/src/main/java/article1be/review/service/ReviewService.java
Labels: :new: feat, :1234: chore

#71 chore : #70 관리자 조회 기능 수정
  article1_be/article1-be/src/main/java/article1be/admin/dto/AdminDTO.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminService.java
Labels: :1234: chore

#73 chore : #72 리뷰 신고 기능 삭제
  article1_be/article1-be/src/main/java/article1be/admin/dto/AdminReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminService.java
  article1_be/article1-be/src/main/java/article1be/review/controller/ReviewController.java
  article1_be/article1-be/src/main/java/article1be/review/dto/ReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/review/entity/Review.java
  article1_be/article1-be/src/main/java/article1be/review/service/ReviewService.java
Labels: :1234: chore

#74 feat: #67 신고 기능 개발
  .gitignore
  article1_be/article1-be/src/main/java/article1be/blame/BlameRepository.java
  article1_be/article1-be/src/main/java/article1be/blame/controller/BlameController.java
  article1_be/article1-be/src/main/java/article1be/blame/dto/BlameDTO.java
  article1_be/article1-be/src/main/java/article1be/blame/entity/Blame.java
  article1_be/article1-be/src/main/java/article1be/blame/service/BlameService.java
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/review/entity/Review.java
  article1_be/article1-be/src/main/resources/application-aws.yml
  article1_be/article1-be/src/main/resources/application.yml
Labels: :new: feat

#77 feat: #75, #76 Swagger 태그 추가
  article1_be/article1-be/src/main/java/article1be/blame/controller/BlameController.java
  article1_be/article1-be/src/main/java/article1be/board/controller/BoardController.java
  article1_be/article1-be/src/main/java/article1be/reply/controller/ReplyController.java
  article1_be/article1-be/src/main/java/article1be/review/controller/ReviewController.java
Labels: :new: feat, :rainbow: style

#78 feat : #76 유저 스타일 및 조건에 따른 조회 수정
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminReviewService.java
  article1_be/article1-be/src/main/java/article1be/blame/repository/BlameRepository.java
  article1_be/article1-be/src/main/java/article1be/blame/service/BlameService.java
  article1_be/article1-be/src/main/java/article1be/review/dto/ReviewDTO.java
  article1_be/article1-be/src/main/java/article1be/review/entity/Review.java
  article1_be/article1-be/src/main/java/article1be/review/service/ReviewService.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserDataController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserDataDTO.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserCondition.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserStyle.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserDataService.java
Labels: :recycle: refactor, :new: feat, :1234: chore

#86 [Feat/header/#69] 헤더 생성, 프론트엔드 src 경로지정 @, vite로 env 파일 불러오기
  article1_fe/article1-fe/package-lock.json
  article1_fe/article1-fe/package.json
  article1_fe/article1-fe/src/App.vue
  article1_fe/article1-fe/src/assets/images/Logo.png
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/config/test
  article1_fe/article1-fe/src/config/vite.config.js
  article1_fe/article1-fe/src/main.js
  article1_fe/article1-fe/src/views/main/MainView.vue
  article1_fe/article1-fe/vite.config.js
Labels: :hammer_and_wrench: fix, :new: feat, :1234: chore

#90 [chore] #89 스웨거 수정
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminController.java
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminReviewController.java
  article1_be/article1-be/src/main/java/article1be/review/controller/ReviewController.java
Labels: :1234: chore

#93 feat: 로그아웃, 선호도 조회, 선호도 수정 기능 구현
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserDataController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/PreferenceResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserDataDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserPreferDTO.java
  article1_be/article1-be/src/main/java/article1be/user/entity/Condition.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserCondition.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserStyle.java
  article1_be/article1-be/src/main/java/article1be/user/repository/ConditionRepository.java
  article1_be/article1-be/src/main/java/article1be/user/repository/StyleRepository.java
  article1_be/article1-be/src/main/java/article1be/user/repository/UserRepository.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserDataService.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_be/article1-be/src/main/resources/application.yml
Labels: :wastebasket: delete, :new: feat

#96 feat: MethodArgumentNotValidException Handler 생성
  article1_be/article1-be/src/main/java/article1be/common/exception/GlobalExceptionHandler.java
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
Labels: :new: feat

#99 [REFACTOR] 추천 알고리즘 리펙토링
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
  article1_be/article1-be/src/main/java/article1be/outfit/controller/OutfitGuestController.java
  article1_be/article1-be/src/main/java/article1be/outfit/controller/OutfitUserController.java
  article1_be/article1-be/src/main/java/article1be/outfit/dto/OutfitRequestDTO.java
  article1_be/article1-be/src/main/java/article1be/outfit/dto/OutfitSelectionRequestDTO.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/SelectOutfit.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/SelectRecord.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/OutfitRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/OutfitStyleRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectOutfitRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectRecordRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitSelectionService.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitService.java
Labels: :recycle: refactor, :new: feat

#100 feat: 게시판 UI 개발
  article1_be/article1-be/src/main/java/article1be/board/dto/BoardDTO.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
  article1_be/article1-be/src/main/resources/application.yml
  article1_fe/article1-fe/src/App.vue
  article1_fe/article1-fe/src/components/board/BoardLi.vue
  article1_fe/article1-fe/src/components/board/BoardNoticeLi.vue
  article1_fe/article1-fe/src/components/board/Container.vue
  article1_fe/article1-fe/src/components/board/ContentArea.vue
  article1_fe/article1-fe/src/components/board/FileUpload.vue
  article1_fe/article1-fe/src/components/board/InputBox.vue
  article1_fe/article1-fe/src/components/board/NormalButton.vue
  article1_fe/article1-fe/src/components/board/RegisterInput.vue
  article1_fe/article1-fe/src/components/board/SmallButton.vue
  article1_fe/article1-fe/src/components/board/TitleBar.vue
  article1_fe/article1-fe/src/components/common/Pagination.vue
  article1_fe/article1-fe/src/components/reply/ReplyInput.vue
  article1_fe/article1-fe/src/components/reply/ReplyLi.vue
  article1_fe/article1-fe/src/router/boardRouter.js
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/views/SituationView.vue
  article1_fe/article1-fe/src/views/board/BoardDetail.vue
  article1_fe/article1-fe/src/views/board/BoardList.vue
  article1_fe/article1-fe/src/views/board/BoardRegister.vue
  article1_fe/article1-fe/src/views/location/MapWithDateView.vue
Labels: :new: feat

#102 refactor: Security 수정 및 검증
  article1_be/article1-be/build.gradle
  article1_be/article1-be/src/main/java/article1be/config/PrincipalDetails.java
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/security/dto/ExceptionResponse.java
  article1_be/article1-be/src/main/java/article1be/security/filter/JwtAuthenticationProcessingFilter.java
  article1_be/article1-be/src/main/java/article1be/security/handler/JwtAccessDeniedHandler.java
  article1_be/article1-be/src/main/java/article1be/security/handler/JwtAuthenticationEntryPoint.java
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginFailureHandler.java
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_be/article1-be/src/main/java/article1be/security/util/JwtUtil.java
  article1_be/article1-be/src/main/java/article1be/security/util/SecurityUtil.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserUpdateDTO.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserAuth.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserGender.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserSocialSite.java
  article1_be/article1-be/src/main/java/article1be/user/entity/UserState.java
  article1_be/article1-be/src/main/java/article1be/user/repository/UserRepository.java
  article1_be/article1-be/src/main/java/article1be/user/service/SocialLoginService.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_be/article1-be/src/main/java/article1be/user/userInfo/OAuth2UserInfo.java
Labels: :recycle: refactor, :new: feat, :rainbow: style

#107 [FEAT] 게스트, 회원 복장 추천 화면 구현
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/OutfitSituation.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/OutfitStyle.java
  article1_be/article1-be/src/main/java/article1be/outfit/entity/SelectOutfit.java
  article1_fe/article1-fe/src/assets/images/outfits/1.png
  article1_fe/article1-fe/src/assets/images/outfits/12.png
  article1_fe/article1-fe/src/assets/images/outfits/6.png
  article1_fe/article1-fe/src/assets/images/outfits/7.png
  article1_fe/article1-fe/src/components/outfit/recommend/GuestOutfitRecommendation.vue
  article1_fe/article1-fe/src/components/outfit/recommend/OutfitRecommendationList.vue
  article1_fe/article1-fe/src/components/outfit/recommend/UserOutfitRecommendation.vue
  article1_fe/article1-fe/src/components/outfit/setting/DatePicker.vue
  article1_fe/article1-fe/src/components/outfit/setting/kakaoMap.vue
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/store/selectedInfoStore.js
  article1_fe/article1-fe/src/views/outfit/recommend/OutfitRecommendationResult.vue
  article1_fe/article1-fe/src/views/outfit/setting/MapWithDateView.vue
  article1_fe/article1-fe/src/views/outfit/setting/SituationView.vue
Labels: :recycle: refactor, :new: feat, :1234: chore

#109 feat: 프론트 MYPAGE 화면 구성, 라우터 설정, 스타일 이미지 추가
  article1_fe/article1-fe/package-lock.json
  article1_fe/article1-fe/src/assets/images/preference/Condition-Cold.png
  article1_fe/article1-fe/src/assets/images/preference/Style-Casual.png
  article1_fe/article1-fe/src/assets/images/preference/Style-Formal.png
  article1_fe/article1-fe/src/components/user/UserDetail.vue
  article1_fe/article1-fe/src/components/user/UserOutfitList.vue
  article1_fe/article1-fe/src/components/user/UserOutfitStats.vue
  article1_fe/article1-fe/src/components/user/UserPost.vue
  article1_fe/article1-fe/src/components/user/UserPreference.vue
  article1_fe/article1-fe/src/components/user/UserReview.vue
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/router/mypageRouter.js
  article1_fe/article1-fe/src/router/userRouter.js
  article1_fe/article1-fe/src/views/user/MyPageLayout.vue
  article1_fe/article1-fe/src/views/user/UserLogin.vue
Labels: :new: feat

#111 chore: import 경로 수정
  article1_fe/article1-fe/src/router/index.js
Labels: :1234: chore

#116 feat: 소셜 로그인 화면 구현
  article1_fe/article1-fe/src/assets/images/user/Condition-Cold.png
  article1_fe/article1-fe/src/assets/images/user/Style-Casual.png
  article1_fe/article1-fe/src/assets/images/user/Style-Formal.png
  article1_fe/article1-fe/src/assets/images/user/google-logo.png
  article1_fe/article1-fe/src/assets/images/user/kakao-logo.png
  article1_fe/article1-fe/src/assets/images/user/naver-logo.png
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/views/user/UserLogin.vue
Labels: :new: feat

#118 [Refector/weather dto/#104] DTO 내용 변경, 시간별 날씨 정확도 상승
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherAirDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/OpenWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ResponseMainWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/dto/weathers/WeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/router/index.js
Labels: :recycle: refactor, :1234: chore

#123 CHORE : #119 Security 수정
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/security/filter/JwtAuthenticationProcessingFilter.java
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_be/article1-be/src/main/java/article1be/security/util/JwtUtil.java
  article1_be/article1-be/src/main/java/article1be/security/util/SecurityUtil.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserDataDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/UserPreferDTO.java
  article1_be/article1-be/src/main/java/article1be/user/entity/Condition.java
  article1_be/article1-be/src/main/java/article1be/user/entity/User.java
  article1_be/article1-be/src/main/java/article1be/user/repository/ConditionRepository.java
  article1_be/article1-be/src/main/java/article1be/user/service/SocialLoginService.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_be/article1-be/src/main/java/article1be/user/userInfo/GoogleUserInfo.java
  article1_be/article1-be/src/main/java/article1be/user/userInfo/KakaoUserInfo.java
  article1_be/article1-be/src/main/java/article1be/user/userInfo/NaverUserInfo.java
  article1_be/article1-be/src/main/resources/application.yml
Labels: :wastebasket: delete, :rainbow: style, :1234: chore

#125 feat: authStore 피니아 개발
  article1_be/article1-be/src/main/java/article1be/blame/controller/BlameController.java
  article1_be/article1-be/src/main/java/article1be/blame/service/BlameService.java
  article1_be/article1-be/src/main/java/article1be/board/controller/BoardController.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
  article1_be/article1-be/src/main/java/article1be/reply/dto/ReplyDTO.java
  article1_be/article1-be/src/main/java/article1be/reply/entity/Reply.java
  article1_be/article1-be/src/main/java/article1be/reply/service/ReplyService.java
  article1_fe/article1-fe/src/components/board/ContentArea.vue
  article1_fe/article1-fe/src/components/board/DeleteModal.vue
  article1_fe/article1-fe/src/components/board/FileUpload.vue
  article1_fe/article1-fe/src/components/board/RegisterInput.vue
  article1_fe/article1-fe/src/components/board/TitleBar.vue
  article1_fe/article1-fe/src/components/reply/ReplyInput.vue
  article1_fe/article1-fe/src/components/reply/ReplyLi.vue
  article1_fe/article1-fe/src/store/authStore.js
  article1_fe/article1-fe/src/views/board/BoardDetail.vue
  article1_fe/article1-fe/src/views/board/BoardList.vue
  article1_fe/article1-fe/src/views/board/BoardRegister.vue
  article1_fe/article1-fe/src/views/user/UserLogin.vue
Labels: :new: feat

#129 [Feat/weather component/#120] fix: 날짜에 맞는 날씨 안불러와지는 오류 수정
  article1_be/article1-be/src/main/java/article1be/common/exception/ErrorCode.java
  article1_be/article1-be/src/main/java/article1be/common/utils/DateTimeUtil.java
  article1_be/article1-be/src/main/java/article1be/openweather/controller/OpenWeatherController.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
  article1_be/article1-be/src/main/java/article1be/outfit/service/OutfitService.java
  article1_be/article1-be/src/main/resources/Schema.sql
  article1_be/article1-be/src/main/resources/data.sql
  article1_fe/article1-fe/src/components/WeatherTab.vue
  article1_fe/article1-fe/src/components/outfit/recommend/UserOutfitRecommendation.vue
  article1_fe/article1-fe/src/router/mainRouter.js
  article1_fe/article1-fe/src/store/selectedInfoStore.js
Labels: :hammer_and_wrench: fix, :recycle: refactor

#133 feat: #131 pinia 수정 및 로그인시 로컬스토리지 저장, 로그인 성공 핸들러 헤더아닌 쿠키로 반환하게 설정
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_fe/article1-fe/src/App.vue
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/store/authStore.js
  article1_fe/article1-fe/src/views/main/MainView.vue
Labels: :new: feat

#136 feat: #120 날씨 컴포넌트 완성, refector: 로그아웃시 쿠키 제거 추가
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/components/WeatherTab.vue
  article1_fe/article1-fe/src/views/main/MainView.vue
Labels: :recycle: refactor, :new: feat

#139 feat: #132 관리자 신고 프론트앤드 구현
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminBoardController.java
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminController.java
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminReplyController.java
  article1_be/article1-be/src/main/java/article1be/admin/controller/AdminReviewController.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminBoardService.java
  article1_be/article1-be/src/main/java/article1be/admin/service/AdminReplyService.java
  article1_be/article1-be/src/main/java/article1be/blame/dto/BlameDTO.java
  article1_be/article1-be/src/main/java/article1be/blame/entity/Blame.java
  article1_be/article1-be/src/main/java/article1be/blame/service/BlameService.java
  article1_be/article1-be/src/main/java/article1be/board/controller/BoardController.java
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/board/repository/BoardRepository.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
  article1_be/article1-be/src/main/java/article1be/reply/controller/ReplyController.java
  article1_be/article1-be/src/main/java/article1be/reply/entity/Reply.java
  article1_be/article1-be/src/main/java/article1be/reply/repository/ReplyRepository.java
  article1_be/article1-be/src/main/java/article1be/reply/service/ReplyService.java
  article1_fe/article1-fe/src/components/blame/BlameLi.vue
  article1_fe/article1-fe/src/components/blame/Selection.vue
  article1_fe/article1-fe/src/components/blame/TopBar.vue
  article1_fe/article1-fe/src/components/board/TitleBar.vue
  article1_fe/article1-fe/src/router/blameRouter.js
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/views/blame/BlameList.vue
  article1_fe/article1-fe/src/views/board/BoardDetail.vue
Labels: :new: feat

#140 chore: #138 관리자 공지사항 작성 로직 구현
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
Labels: :1234: chore

#142 chore: 배경을 제거하고 조회 결과가 없을 때, UI에 표시해주는 코드 추가
  article1_fe/article1-fe/src/views/board/BoardList.vue
Labels: :1234: chore

#144 hotFix: 신고 기능 500 에러 수정
  article1_be/article1-be/src/main/java/article1be/blame/repository/BlameRepository.java
  article1_be/article1-be/src/main/java/article1be/blame/service/BlameService.java
Labels: :hammer_and_wrench: fix

#147 [REFACTOR] 복장 추천 routing처리
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/components/outfit/recommend/GuestOutfitRecommendation.vue
  article1_fe/article1-fe/src/router/index.js
  article1_fe/article1-fe/src/router/outfitRouter.js
  article1_fe/article1-fe/src/views/outfit/setting/SituationView.vue
Labels: :recycle: refactor

#149 Feat/image change/#137 날씨별로 배경이미지가 변경 되는 기능 추가하기, 로그 인 오류 수정
  article1_be/article1-be/src/main/java/article1be/openweather/dto/response/ResponseMainWeatherDTO.java
  article1_be/article1-be/src/main/java/article1be/openweather/service/OpenWeatherService.java
  article1_fe/article1-fe/src/App.vue
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/components/WeatherTab.vue
  article1_fe/article1-fe/src/store/authStore.js
  article1_fe/article1-fe/src/store/useWeatherStore.js
  article1_fe/article1-fe/src/views/main/MainView.vue
Labels: :new: feat, :1234: chore

#152 [FEAT] 회원별 선택기록 조회, 선택 복장 조회 기능 구현
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectOutfitRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectRecordRepository.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/SelectOutfitResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/SelectRecordResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
Labels: :new: feat

#155 [TEST] 복장 선택 결과 저장 test 코드 작성
  article1_be/article1-be/src/main/java/article1be/test/controller/test.md
  article1_be/article1-be/src/main/java/article1be/test/dto/test.md
  article1_be/article1-be/src/main/java/article1be/test/repository/test.md
  article1_be/article1-be/src/main/java/article1be/test/service/test.md
  article1_be/article1-be/src/test/java/article1be/Article1BeApplicationTests.java
  article1_be/article1-be/src/test/java/article1be/outfit/service/OutfitSelectionServiceTest.java
Labels: :wastebasket: delete, :m: test

#158 [REFACTOR] 추천 result view 구현
  article1_fe/article1-fe/src/components/outfit/recommend/GuestOutfitRecommendation.vue
  article1_fe/article1-fe/src/components/outfit/recommend/UserOutfitRecommendation.vue
  article1_fe/article1-fe/src/router/outfitRouter.js
  article1_fe/article1-fe/src/store/selectedInfoStore.js
  article1_fe/article1-fe/src/views/outfit/recommend/OutfitRecommendationResult.vue
  article1_fe/article1-fe/src/views/outfit/setting/SituationView.vue
Labels: :recycle: refactor, :new: feat

#161 feat: 회원가입 시 추가정보 등록 화면, 마이페이지 회원정보 및 선호도 화면 구현
  article1_be/article1-be/src/main/java/article1be/user/dto/PreferenceResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_fe/article1-fe/src/assets/images/user/Condition-Hot.png
  article1_fe/article1-fe/src/assets/images/user/Style-Sporty.png
  article1_fe/article1-fe/src/components/user/EditPreference.vue
  article1_fe/article1-fe/src/components/user/PreferenceForm.vue
  article1_fe/article1-fe/src/components/user/UserDetail.vue
  article1_fe/article1-fe/src/components/user/UserPreference.vue
  article1_fe/article1-fe/src/router/mypageRouter.js
  article1_fe/article1-fe/src/router/userRouter.js
  article1_fe/article1-fe/src/views/user/UserData.vue
  article1_fe/article1-fe/src/views/user/UserLogin.vue
Labels: :new: feat, :1234: chore

#162 CHORE : #119 Security 수정
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
Labels: :1234: chore

#164 TEST : #163 회원 관련 테스트 코드 추가
  article1_be/article1-be/src/main/java/article1be/outfit/entity/Style.java
  article1_be/article1-be/src/main/java/article1be/user/entity/Condition.java
  article1_be/article1-be/src/test/java/article1be/user/service/UserServiceTest.java
Labels: :m: test

#166 feat: 탈퇴 시 로그아웃 기능 구현 및 에러 처리
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_fe/article1-fe/src/components/user/EditPreference.vue
  article1_fe/article1-fe/src/components/user/UserDetail.vue
  article1_fe/article1-fe/src/router/userRouter.js
  article1_fe/article1-fe/src/views/user/BannedUserError.vue
  article1_fe/article1-fe/src/views/user/DeletedUserError.vue
  article1_fe/article1-fe/src/views/user/UserData.vue
Labels: :new: feat

#167 feat: #143 게시판 관련 테스트 코드 작성
  article1_be/article1-be/src/test/java/article1be/admin/service/AdminBoardServiceTest.java
  article1_be/article1-be/src/test/java/article1be/admin/service/AdminReplyServiceTest.java
  article1_be/article1-be/src/test/java/article1be/board/service/BoardServiceTest.java
  article1_be/article1-be/src/test/java/article1be/reply/service/ReplyServiceTest.java
  article1_fe/article1-fe/src/views/board/BoardList.vue
Labels: :new: feat

#169 feat: #168 신고 기능 테스트코드 작성
  article1_be/article1-be/src/test/java/article1be/blame/service/BlameServiceTest.java
Labels: :new: feat

#172 feat: #171 MY PAGE 아웃핏 이력조회, 리뷰 조회, 게시글 조회 화면 구현, paging 처리 구현
  article1_be/article1-be/src/main/java/article1be/user/dto/SelectOutfitResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_fe/article1-fe/src/components/common/Pagination.vue
  article1_fe/article1-fe/src/components/user/UserOutfitList.vue
  article1_fe/article1-fe/src/components/user/UserPost.vue
  article1_fe/article1-fe/src/components/user/UserReview.vue
Labels: :new: feat

#182 fix: #181 게시글, 댓글, 사진 삭제 시 삭제일 미등록되는 오류 수정
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/board/entity/Picture.java
  article1_be/article1-be/src/main/java/article1be/board/service/BoardService.java
  article1_be/article1-be/src/main/java/article1be/reply/entity/Reply.java
  article1_be/article1-be/src/main/java/article1be/reply/service/ReplyService.java
Labels: :hammer_and_wrench: fix

#183 [FEAT] 관리자 라우터 처리
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/components/blame/BlameLi.vue
  article1_fe/article1-fe/src/store/authStore.js
Labels: :recycle: refactor, :new: feat

#187 docs: #185 README 초안 작성
  README.md
Labels: :memo: docs

#189 [REFACTOR] 첫 소셜로그인시 정보 입력으로 리다이렉트 추가
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_fe/article1-fe/src/views/user/UserData.vue
Labels: :recycle: refactor, :new: feat

#194 feat: 게시글 수정 버튼 추가
  article1_be/article1-be/src/test/java/article1be/blame/service/BlameServiceTest.java
  article1_fe/article1-fe/src/components/board/ContentArea.vue
  article1_fe/article1-fe/src/router/boardRouter.js
  article1_fe/article1-fe/src/views/board/BoardModify.vue
Labels: :new: feat

#199 chore: #197 DDL, DML 수정
  article1_be/article1-be/src/main/resources/Schema.sql
  article1_be/article1-be/src/main/resources/data.sql
Labels: :1234: chore

#201 fix: 레포지토리 메소드명 오타 수정
  article1_be/article1-be/src/main/java/article1be/blame/exception/AlreadyReportedException.java
  article1_be/article1-be/src/main/java/article1be/blame/repository/BlameRepository.java
  article1_be/article1-be/src/test/java/article1be/blame/service/BlameServiceTest.java
Labels: :hammer_and_wrench: fix

#202 [FEAT] 복장 선택 통계 API, 페이지 추가
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectOutfitCustomRepository.java
  article1_be/article1-be/src/main/java/article1be/outfit/repository/SelectOutfitRepository.java
  article1_be/article1-be/src/main/java/article1be/user/controller/UserController.java
  article1_be/article1-be/src/main/java/article1be/user/dto/CategoryStatsDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/OutfitStatsDTO.java
  article1_be/article1-be/src/main/java/article1be/user/dto/SelectOutfitStatsResponseDTO.java
  article1_be/article1-be/src/main/java/article1be/user/service/UserService.java
  article1_fe/article1-fe/src/assets/images/outfits/icons/accessory.png
  article1_fe/article1-fe/src/assets/images/outfits/icons/bottom.png
  article1_fe/article1-fe/src/assets/images/outfits/icons/outerwear.png
  article1_fe/article1-fe/src/assets/images/outfits/icons/shoes.png
  article1_fe/article1-fe/src/assets/images/outfits/icons/top.png
  article1_fe/article1-fe/src/components/user/UserOutfitStats.vue
Labels: :new: feat

#206 chore: 이미지 크기 조절
  article1_fe/article1-fe/src/components/user/PreferenceForm.vue
Labels: :1234: chore

#208 fix: #200 게시글, 댓글 테스트 코드 수정
  article1_be/article1-be/src/main/java/article1be/board/entity/Board.java
  article1_be/article1-be/src/main/java/article1be/reply/entity/Reply.java
  article1_be/article1-be/src/main/java/article1be/reply/service/ReplyService.java
  article1_be/article1-be/src/test/java/article1be/board/service/BoardServiceTest.java
  article1_be/article1-be/src/test/java/article1be/reply/service/ReplyServiceTest.java
  article1_fe/article1-fe/src/views/board/BoardDetail.vue
Labels: :hammer_and_wrench: fix

#210 feat: #209 필터링 기능 추가
  article1_fe/article1-fe/src/components/board/Container.vue
  article1_fe/article1-fe/src/views/board/BoardList.vue
Labels: :new: feat

#213 chore: #212 MY PAGE 리뷰 조회, 게시글 조회 화면 수정
  article1_fe/article1-fe/src/components/Header.vue
  article1_fe/article1-fe/src/components/user/UserPost.vue
  article1_fe/article1-fe/src/components/user/UserReview.vue
  article1_fe/article1-fe/src/views/review/ReviewList.vue
  article1_fe/article1-fe/src/views/user/MyPageLayout.vue
Labels: :1234: chore

#214 chore: UI 수정으로 인한 재촬영
  images/리뷰/리뷰 닉네임 필터링.gif
  images/리뷰/리뷰 신고.gif
  images/리뷰/리뷰 위치 필터링.gif
  images/리뷰/전체 리뷰 조회.gif
  images/마이페이지/마이페이지 게시글 조회.gif
  images/마이페이지/마이페이지 리뷰 조회.gif
Labels: :1234: chore

#215 docs: #185 README 1차 작성
  README.md
Labels: :memo: docs

#218 chore: #217 MY PAGE 아웃핏 이력 조회 화면 수정
  article1_fe/article1-fe/src/components/user/UserOutfitList.vue
Labels: :1234: chore

#220 fix: 파일명 오기입 수정
  images/마이페이지/마이페이지 아웃핏 통계 조회.gif
  images/마이페이지/마이페이지 이력조회.gif
Labels: :hammer_and_wrench: fix

#222 docs: README 내용 수정
  README.md
Labels: :memo: docs

#225 docs: README 헤더 수정, 회고 추가
  README.md
Labels: :memo: docs

#227 Feat/dockerfile/#153
  .gitignore
  article1_be/article1-be/Dockerfile
  article1_be/article1-be/src/main/java/article1be/config/SecurityConfig.java
  article1_be/article1-be/src/main/java/article1be/security/handler/OAuth2LoginSuccessHandler.java
  article1_be/article1-be/src/main/resources/application.yml
  article1_fe/article1-fe/Dockerfile
  article1_fe/article1-fe/nginx.conf
  article1_fe/article1-fe/src/components/WeatherTab.vue
  article1_fe/article1-fe/src/components/outfit/recommend/GuestOutfitRecommendation.vue
  article1_fe/article1-fe/src/components/reply/ReplyInput.vue
  article1_fe/article1-fe/src/components/reply/ReplyLi.vue
  article1_fe/article1-fe/src/components/user/EditPreference.vue
  article1_fe/article1-fe/src/components/user/PreferenceForm.vue
  article1_fe/article1-fe/src/components/user/UserDetail.vue
  article1_fe/article1-fe/src/components/user/UserOutfitList.vue
  article1_fe/article1-fe/src/components/user/UserPost.vue
  article1_fe/article1-fe/src/components/user/UserReview.vue
  article1_fe/article1-fe/src/config/vite.config.js
  article1_fe/article1-fe/src/main.js
  article1_fe/article1-fe/src/views/board/BoardDetail.vue
  article1_fe/article1-fe/src/views/board/BoardList.vue
  article1_fe/article1-fe/src/views/board/BoardModify.vue
  article1_fe/article1-fe/src/views/board/BoardRegister.vue
  article1_fe/article1-fe/src/views/main/MainView.vue
  article1_fe/article1-fe/src/views/user/UserData.vue
  article1_fe/article1-fe/src/views/user/UserLogin.vue
  article1_k8s/backend-dep.yml
  article1_k8s/backend-ingress.yml
  article1_k8s/backend-service.yml
  article1_k8s/configmaps/my.cnf
  article1_k8s/frontend-dep.yml
  article1_k8s/frontend-ingress.yml
  article1_k8s/frontend-service.yml
  article1_k8s/mariadb-dep.yml
  article1_k8s/mariadb-pvc.yml
  article1_k8s/mariadb-service.yml
Labels: :recycle: refactor, :new: feat, :1234: chore

#228 docs: README 수정
  README.md
Labels: :memo: docs
